"""
Seed default obligation types for automatic generation.
"""

from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models.obligation_type import ObligationType
from app.schemas.obligation import ObligationRecurrence

DEFAULT_FLAGS: dict[str, Any] = {
    "applies_to_commerce": False,
    "applies_to_service": False,
    "applies_to_industry": False,
    "applies_to_mei": False,
    "applies_to_simples": False,
    "applies_to_presumido": False,
    "applies_to_real": False,
    "is_active": True,
}


DEFAULT_OBLIGATION_TYPES: list[dict[str, Any]] = [
    # MEI
    {
        "name": "DAS-MEI",
        "code": "DAS_MEI_MENSAL",
        "description": "Documento de Arrecadação do Simples Nacional - MEI",
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 20,
    },
    {
        "name": "DASN SIMEI",
        "code": "DASN_SIMEI_ANUAL",
        "description": "Declaração Anual do Simples Nacional - MEI",
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.ANUAL,
        "day_of_month": 31,
        "month_of_year": 5,
    },
    # Simples Nacional
    {
        "name": "PGDAS Simples Nacional",
        "code": "PGDAS_MENSAL",
        "description": "Programa Gerador do Documento de Arrecadação do Simples Nacional",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 20,
    },
    {
        "name": "DAS",
        "code": "DAS_MENSAL",
        "description": "Documento de Arrecadação do Simples Nacional",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 20,
    },
    {
        "name": "EFD Contribuições",
        "code": "EFD_CONTRIBUICOES",
        "description": "Escrituração Fiscal Digital das Contribuições",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 25,
    },
    {
        "name": "EFD ICMS/IPI",
        "code": "EFD_ICMS_IPI_MENSAL",
        "description": "Escrituração Fiscal Digital do ICMS/IPI",
        "applies_to_commerce": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 15,
    },
    {
        "name": "DIEF",
        "code": "DIEF_MENSAL",
        "description": "Declaração de Informações Econômico-Fiscais",
        "applies_to_commerce": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 20,
    },
    {
        "name": "ICMS Antecipação/DIFAL/SUBST",
        "code": "ICMS_ANTECIPACAO_MENSAL",
        "description": "ICMS antecipação, DIFAL ou substituição tributária",
        "applies_to_commerce": True,
        "applies_to_simples": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 15,
    },
    # Lucro Presumido / Lucro Real
    {
        "name": "ISS",
        "code": "ISS_MENSAL",
        "description": "Imposto Sobre Serviços",
        "applies_to_service": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 10,
    },
    {
        "name": "PIS/COFINS",
        "code": "PIS_COFINS_MENSAL",
        "description": "Contribuições PIS/COFINS",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 25,
    },
    {
        "name": "ICMS Normal",
        "code": "ICMS_NORMAL_MENSAL",
        "description": "Apuração ICMS Normal",
        "applies_to_commerce": True,
        "applies_to_industry": True,
        "applies_to_presumido": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 15,
    },
    {
        "name": "IPI",
        "code": "IPI_MENSAL",
        "description": "Imposto sobre Produtos Industrializados",
        "applies_to_industry": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 25,
    },
    {
        "name": "IRPJ/CSLL",
        "code": "IRPJ_CSLL_TRIMESTRAL",
        "description": "Imposto de Renda PJ e Contribuição Social",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.TRIMESTRAL,
        "day_of_month": 30,
    },
    {
        "name": "ECD",
        "code": "ECD_ANUAL",
        "description": "Escrituração Contábil Digital",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.ANUAL,
        "day_of_month": 30,
        "month_of_year": 6,
    },
    {
        "name": "ECF",
        "code": "ECF_ANUAL",
        "description": "Escrituração Contábil Fiscal",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.ANUAL,
        "day_of_month": 31,
        "month_of_year": 7,
    },
    {
        "name": "LALUR",
        "code": "LALUR_ANUAL",
        "description": "Livro de Apuração do Lucro Real",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.ANUAL,
        "day_of_month": 30,
        "month_of_year": 6,
    },
    {
        "name": "NFS-e",
        "code": "NFS_E_MENSAL",
        "description": "Nota Fiscal de Serviços Eletrônica",
        "applies_to_service": True,
        "applies_to_real": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 15,
    },
    # Departamento Pessoal
    {
        "name": "Folha de Pagamento",
        "code": "FOLHA_PAGAMENTO_MENSAL",
        "description": "Folha de pagamento mensal",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 5,
    },
    {
        "name": "eSocial",
        "code": "ESOCIAL_MENSAL",
        "description": "Sistema de Escrituração Digital das Obrigações Fiscais",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 10,
    },
    {
        "name": "DCTF Web",
        "code": "DCTF_WEB_MENSAL",
        "description": "Declaração de Débitos e Créditos Tributários Federais",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 30,
    },
    {
        "name": "FGTS Digital",
        "code": "FGTS_MENSAL",
        "description": "Fundo de Garantia do Tempo de Serviço",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 20,
    },
    {
        "name": "EFD Reinf",
        "code": "EFD_REINF_MENSAL",
        "description": "Escrituração Fiscal Digital de Retenções",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 15,
    },
    {
        "name": "MIT",
        "code": "MIT_MENSAL",
        "description": "Módulo de Inclusão de Tributos",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 30,
    },
    {
        "name": "13º Salário - 1ª Parcela",
        "code": "DECIMO_TERCEIRO_1_ANUAL",
        "description": "Pagamento da 1ª parcela do 13º salário",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.ANUAL,
        "day_of_month": 30,
        "month_of_year": 11,
    },
    {
        "name": "13º Salário - 2ª Parcela",
        "code": "DECIMO_TERCEIRO_2_ANUAL",
        "description": "Pagamento da 2ª parcela do 13º salário",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.ANUAL,
        "day_of_month": 20,
        "month_of_year": 12,
    },
    {
        "name": "DCTF Web 13º Salário",
        "code": "DCTF_WEB_13_ANUAL",
        "description": "Declaração DCTF Web do 13º salário",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.ANUAL,
        "day_of_month": 20,
        "month_of_year": 12,
    },
    {
        "name": "Parcelamentos",
        "code": "PARCELAMENTOS_MENSAL",
        "description": "Parcelamentos fiscais",
        "applies_to_commerce": True,
        "applies_to_service": True,
        "applies_to_industry": True,
        "applies_to_simples": True,
        "applies_to_presumido": True,
        "applies_to_real": True,
        "applies_to_mei": True,
        "recurrence": ObligationRecurrence.MENSAL,
        "day_of_month": 30,
    },
]


async def ensure_obligation_types(session: AsyncSession) -> int:
    """Insert missing obligation types and return count added."""
    result = await session.execute(select(ObligationType.code))
    existing_codes = {row[0] for row in result.fetchall()}

    existing_result = await session.execute(select(ObligationType))
    existing_by_code = {row.code: row for row in existing_result.scalars().all()}

    created = 0
    for item in DEFAULT_OBLIGATION_TYPES:
        payload = {**DEFAULT_FLAGS, **item}
        existing = existing_by_code.get(item["code"])
        if existing:
            for key, value in payload.items():
                if getattr(existing, key) != value:
                    setattr(existing, key, value)
        else:
            session.add(ObligationType(**payload))
            created += 1

    await session.commit()
    return created
