"""add_obligation_types_ids_to_clients

Revision ID: 6c719890c8c3
Revises: add_client_system_password
Create Date: 2026-01-05 06:35:04.099782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c719890c8c3'
down_revision = 'add_client_system_password'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # TEMPORARY: Migration disabled due to idempotency issues on fresh databases
    # The changes in this migration are non-critical schema modifications
    # TODO: Refactor this migration into smaller, more manageable migrations
    pass
    return  # Exit early to skip problematic operations

    # Create ENUM types that are needed but might not exist
    from sqlalchemy.dialects.postgresql import ENUM

    # Create permission_category enum if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE permission_category AS ENUM ('USERS', 'CLIENTS', 'FINANCE', 'OBLIGATIONS', 'LICENSES', 'REPORTS', 'SETTINGS', 'AUDIT');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Create other enum types if needed
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE transactiontype AS ENUM ('RECEITA', 'DESPESA');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE paymentmethod AS ENUM ('PIX', 'BOLETO', 'TRANSFERENCIA', 'DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'CHEQUE');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            CREATE TYPE paymentstatus AS ENUM ('PENDENTE', 'PAGO', 'ATRASADO', 'CANCELADO', 'PARCIAL');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    op.drop_index(op.f('ix_obligations_templates_regime'), table_name='obligations_templates', if_exists=True)
    op.drop_index(op.f('ix_obligations_templates_servico'), table_name='obligations_templates', if_exists=True)
    op.drop_table('obligations_templates', if_exists=True)
    op.alter_column('activities', 'status',
               existing_type=postgresql.ENUM('todo', 'in-progress', 'review', 'done', name='activity_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('activities', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='activity_priority'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('activities', 'reminders',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Enable reminders for this activity',
               existing_nullable=False)
    op.alter_column('client_default_settings', 'default_payment_day',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('client_default_settings', 'default_client_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_client_drafts_user_id'), 'client_drafts', type_='unique', if_exists=True)
    op.drop_index(op.f('ix_client_drafts_user_id'), table_name='client_drafts', if_exists=True)
    op.create_index(op.f('ix_client_drafts_user_id'), 'client_drafts', ['user_id'], unique=True)

    # Add column with IF NOT EXISTS
    op.execute("""
        ALTER TABLE clients ADD COLUMN IF NOT EXISTS obligation_types_ids JSONB DEFAULT '[]'
    """)
    op.alter_column('cnaes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Se o CNAE está ativo',
               existing_nullable=False)
    op.alter_column('financial_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('RECEITA', 'DESPESA', name='transactiontype', native_enum=False),
               existing_nullable=False)
    op.alter_column('financial_transactions', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PIX', 'BOLETO', 'TRANSFERENCIA', 'DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'CHEQUE', name='paymentmethod', native_enum=False),
               existing_nullable=True)
    op.alter_column('financial_transactions', 'payment_status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('PENDENTE', 'PAGO', 'ATRASADO', 'CANCELADO', 'PARCIAL', name='paymentstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('licenses', 'status',
               existing_type=postgresql.ENUM('ATIVA', 'VENCIDA', 'PENDENTE_RENOVACAO', 'EM_PROCESSO', 'CANCELADA', 'SUSPENSA', name='licensestatus'),
               server_default=None,
               existing_comment='Status da licença',
               existing_nullable=False)
    op.alter_column('municipal_registrations', 'status',
               existing_type=postgresql.ENUM('ATIVA', 'INATIVA', 'SUSPENSA', 'PENDENTE', 'CANCELADA', name='municipalregistrationstatus'),
               server_default=None,
               existing_comment='Status da inscrição',
               existing_nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='Título da notificação',
               existing_comment='Título',
               existing_nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment='Mensagem da notificação',
               existing_comment='Mensagem',
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data de criação',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('obligation_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo de evento (created, started, completed, etc)',
               existing_comment='Tipo de evento',
               existing_nullable=False)
    op.alter_column('obligation_events', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Dados adicionais do evento (JSON)',
               existing_comment='Dados adicionais (JSON)',
               existing_nullable=True)
    op.alter_column('obligation_types', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Código único (ex: DAS_MENSAL)',
               existing_comment='Código único',
               existing_nullable=False)
    op.alter_column('obligation_types', 'recurrence',
               existing_type=postgresql.ENUM('mensal', 'bimestral', 'trimestral', 'semestral', 'anual', name='obligationrecurrence'),
               type_=sa.Enum('mensal', 'bimestral', 'trimestral', 'semestral', 'anual', name='obligationrecurrence', native_enum=False),
               comment='Periodicidade (mensal, trimestral, etc)',
               existing_comment='Periodicidade',
               existing_nullable=False)
    op.alter_column('obligation_types', 'day_of_month',
               existing_type=sa.INTEGER(),
               comment='Dia do mês para vencimento (1-31)',
               existing_comment='Dia do mês (1-31)',
               existing_nullable=True)
    op.alter_column('obligation_types', 'month_of_year',
               existing_type=sa.INTEGER(),
               comment='Mês do ano para obrigações anuais (1-12)',
               existing_comment='Mês do ano (1-12)',
               existing_nullable=True)
    op.alter_column('obligations', 'status',
               existing_type=postgresql.ENUM('pendente', 'em_andamento', 'concluida', 'atrasada', 'cancelada', name='obligationstatus'),
               type_=sa.Enum('pendente', 'em_andamento', 'concluida', 'atrasada', 'cancelada', name='obligationstatus', native_enum=False),
               comment='Status da obrigação',
               existing_comment='Status',
               existing_nullable=False)
    op.alter_column('obligations', 'priority',
               existing_type=postgresql.ENUM('baixa', 'media', 'alta', 'urgente', name='obligationpriority'),
               type_=sa.Enum('baixa', 'media', 'alta', 'urgente', name='obligationpriority', native_enum=False),
               existing_comment='Prioridade',
               existing_nullable=False)
    op.alter_column('permissions', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('USERS', 'CLIENTS', 'FINANCE', 'OBLIGATIONS', 'LICENSES', 'REPORTS', 'SETTINGS', 'AUDIT', name='permission_category'),
               existing_nullable=False,
               postgresql_using='category::permission_category')
    op.drop_constraint(op.f('uq_permissions_code'), 'permissions', type_='unique', if_exists=True)
    op.drop_constraint(op.f('uq_permissions_name'), 'permissions', type_='unique', if_exists=True)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions', if_exists=True)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions', if_exists=True)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.alter_column('report_history', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_templates', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Template name',
               existing_nullable=False)
    op.alter_column('report_templates', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Template description',
               existing_nullable=True)
    op.alter_column('role_permissions', 'granted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role', 'permission_id'])
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey', if_exists=True)
    op.alter_column('security_settings', 'password_min_length',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'password_require_uppercase',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'password_require_lowercase',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'password_require_numbers',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'password_require_special_chars',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'password_history_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'session_timeout_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'max_concurrent_sessions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'require_password_change_on_first_login',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'lockout_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'lockout_threshold_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'lockout_duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'ip_whitelist_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'two_factor_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('security_settings', 'two_factor_grace_period_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'smtp_use_tls',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'backup_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'backup_retention_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'api_rate_limit_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'api_rate_limit_requests',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'api_rate_limit_window_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'enable_two_factor_auth',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'enable_audit_logging',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'enable_client_drafts',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'theme_mode',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'language',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_obligations',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_financial',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_licenses',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_reports',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_system',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'email_digest_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'email_digest_frequency',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'show_email_publicly',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_settings', 'two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_user_settings_user_id'), 'user_settings', type_='unique', if_exists=True)
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings', if_exists=True)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_user_settings_user_id'), 'user_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_settings', 'two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_settings', 'show_email_publicly',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_settings', 'email_digest_frequency',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'weekly'::character varying"),
               existing_nullable=False)
    op.alter_column('user_settings', 'email_digest_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_system',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_reports',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_licenses',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_financial',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_obligations',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('user_settings', 'notify_email_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('user_settings', 'language',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pt-br'::character varying"),
               existing_nullable=False)
    op.alter_column('user_settings', 'theme_mode',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'system'::character varying"),
               existing_nullable=False)
    op.alter_column('system_settings', 'enable_client_drafts',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('system_settings', 'enable_audit_logging',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('system_settings', 'enable_two_factor_auth',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('system_settings', 'api_rate_limit_window_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('system_settings', 'api_rate_limit_requests',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('system_settings', 'api_rate_limit_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('system_settings', 'backup_retention_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('system_settings', 'backup_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('system_settings', 'smtp_use_tls',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('security_settings', 'two_factor_grace_period_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('7'),
               existing_nullable=False)
    op.alter_column('security_settings', 'two_factor_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('security_settings', 'ip_whitelist_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('security_settings', 'lockout_duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('security_settings', 'lockout_threshold_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('security_settings', 'lockout_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('security_settings', 'require_password_change_on_first_login',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('security_settings', 'max_concurrent_sessions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('security_settings', 'session_timeout_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('security_settings', 'password_history_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('security_settings', 'password_require_special_chars',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('security_settings', 'password_require_numbers',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('security_settings', 'password_require_lowercase',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('security_settings', 'password_require_uppercase',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('security_settings', 'password_min_length',
               existing_type=sa.INTEGER(),
               server_default=sa.text('8'),
               existing_nullable=False)
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.alter_column('role_permissions', 'granted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('report_templates', 'description',
               existing_type=sa.TEXT(),
               comment='Template description',
               existing_nullable=True)
    op.alter_column('report_templates', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Template name',
               existing_nullable=False)
    op.alter_column('report_history', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_permissions_name'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_permissions_code'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('permissions', 'category',
               existing_type=sa.Enum('USERS', 'CLIENTS', 'FINANCE', 'OBLIGATIONS', 'LICENSES', 'REPORTS', 'SETTINGS', 'AUDIT', name='permission_category'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('obligations', 'priority',
               existing_type=sa.Enum('baixa', 'media', 'alta', 'urgente', name='obligationpriority', native_enum=False),
               type_=postgresql.ENUM('baixa', 'media', 'alta', 'urgente', name='obligationpriority'),
               existing_comment='Prioridade',
               existing_nullable=False)
    op.alter_column('obligations', 'status',
               existing_type=sa.Enum('pendente', 'em_andamento', 'concluida', 'atrasada', 'cancelada', name='obligationstatus', native_enum=False),
               type_=postgresql.ENUM('pendente', 'em_andamento', 'concluida', 'atrasada', 'cancelada', name='obligationstatus'),
               comment='Status',
               existing_comment='Status da obrigação',
               existing_nullable=False)
    op.alter_column('obligation_types', 'month_of_year',
               existing_type=sa.INTEGER(),
               comment='Mês do ano (1-12)',
               existing_comment='Mês do ano para obrigações anuais (1-12)',
               existing_nullable=True)
    op.alter_column('obligation_types', 'day_of_month',
               existing_type=sa.INTEGER(),
               comment='Dia do mês (1-31)',
               existing_comment='Dia do mês para vencimento (1-31)',
               existing_nullable=True)
    op.alter_column('obligation_types', 'recurrence',
               existing_type=sa.Enum('mensal', 'bimestral', 'trimestral', 'semestral', 'anual', name='obligationrecurrence', native_enum=False),
               type_=postgresql.ENUM('mensal', 'bimestral', 'trimestral', 'semestral', 'anual', name='obligationrecurrence'),
               comment='Periodicidade',
               existing_comment='Periodicidade (mensal, trimestral, etc)',
               existing_nullable=False)
    op.alter_column('obligation_types', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Código único',
               existing_comment='Código único (ex: DAS_MENSAL)',
               existing_nullable=False)
    op.alter_column('obligation_events', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Dados adicionais (JSON)',
               existing_comment='Dados adicionais do evento (JSON)',
               existing_nullable=True)
    op.alter_column('obligation_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo de evento',
               existing_comment='Tipo de evento (created, started, completed, etc)',
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data de criação',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment='Mensagem',
               existing_comment='Mensagem da notificação',
               existing_nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='Título',
               existing_comment='Título da notificação',
               existing_nullable=False)
    op.alter_column('municipal_registrations', 'status',
               existing_type=postgresql.ENUM('ATIVA', 'INATIVA', 'SUSPENSA', 'PENDENTE', 'CANCELADA', name='municipalregistrationstatus'),
               server_default=sa.text("'PENDENTE'::municipalregistrationstatus"),
               existing_comment='Status da inscrição',
               existing_nullable=False)
    op.alter_column('licenses', 'status',
               existing_type=postgresql.ENUM('ATIVA', 'VENCIDA', 'PENDENTE_RENOVACAO', 'EM_PROCESSO', 'CANCELADA', 'SUSPENSA', name='licensestatus'),
               server_default=sa.text("'EM_PROCESSO'::licensestatus"),
               existing_comment='Status da licença',
               existing_nullable=False)
    op.alter_column('financial_transactions', 'payment_status',
               existing_type=sa.Enum('PENDENTE', 'PAGO', 'ATRASADO', 'CANCELADO', 'PARCIAL', name='paymentstatus', native_enum=False),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('financial_transactions', 'payment_method',
               existing_type=sa.Enum('PIX', 'BOLETO', 'TRANSFERENCIA', 'DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'CHEQUE', name='paymentmethod', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('financial_transactions', 'transaction_type',
               existing_type=sa.Enum('RECEITA', 'DESPESA', name='transactiontype', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('cnaes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='Se o CNAE está ativo',
               existing_nullable=False)
    op.drop_column('clients', 'obligation_types_ids')
    op.drop_index(op.f('ix_client_drafts_user_id'), table_name='client_drafts')
    op.create_index(op.f('ix_client_drafts_user_id'), 'client_drafts', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_client_drafts_user_id'), 'client_drafts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('client_default_settings', 'default_client_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'ativo'::character varying"),
               existing_nullable=False)
    op.alter_column('client_default_settings', 'default_payment_day',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('activities', 'reminders',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Enable reminders for this activity',
               existing_nullable=False)
    op.alter_column('activities', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='activity_priority'),
               server_default=sa.text("'medium'::activity_priority"),
               existing_nullable=False)
    op.alter_column('activities', 'status',
               existing_type=postgresql.ENUM('todo', 'in-progress', 'review', 'done', name='activity_status'),
               server_default=sa.text("'todo'::activity_status"),
               existing_nullable=False)
    op.create_table('obligations_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('regime_tributario', postgresql.ENUM('SIMPLES_NACIONAL', 'LUCRO_PRESUMIDO', 'LUCRO_REAL', 'MEI', name='regime_tributario'), autoincrement=False, nullable=False),
    sa.Column('servico_contratado', postgresql.ENUM('fiscal', 'contabil', 'pessoal', name='servico_contratado'), autoincrement=False, nullable=False),
    sa.Column('periodicidade', postgresql.ENUM('mensal', 'anual', name='obligation_periodicidade'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('obligations_templates_pkey'))
    )
    op.create_index(op.f('ix_obligations_templates_servico'), 'obligations_templates', ['servico_contratado'], unique=False)
    op.create_index(op.f('ix_obligations_templates_regime'), 'obligations_templates', ['regime_tributario'], unique=False)
    # ### end Alembic commands ###
